이름: 정한빛  
학번: 202244044

1.titanic 데이터에서 (boolean indexing 사용)  
1) age 열이 25세 이상이고 남성인 행만 구하고  
2) 이중 앞의 5행만 print하는 하는 code를 작성 하시오

In [1]:
import pandas as pd
import seaborn as sns

titanic=sns.load_dataset('titanic')
df=titanic.loc[(titanic['age']>=25) & (titanic['sex']=='male')]
df.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True

2.아래 dataframe df에서   (query  사용)    (선택)  
 age 열이 25세 이상이고 pclass가 3인 데이터만 프린트 하시오,

In [2]:
import pandas as pd
import seaborn as sns

titanic=sns.load_dataset('titanic')
df=titanic.loc[:,['age','pclass']]
df.query('age>=25 and pclass==3')

      age  pclass
2    26.0       3
4    35.0       3
8    27.0       3
13   39.0       3
18   31.0       3
..    ...     ...
873  47.0       3
881  33.0       3
884  25.0       3
885  39.0       3
890  32.0       3

[174 rows x 2 columns]

3.아래와 같은 구조를 갖는  데이터 프레임에서    (원본 객체 변경)  
1) '인문' 열을 추가 하여 영어와 국어 성적의 합계를 저장하고  
2) '과학' 열을 추가 하여 물리와 화학 성적의 합계를 저장하고  
3)  과학 성적으로 내림 차순으로 정렬하고  
4) print하는 code를 작성하시오.   


|이름|국어|영어|물리|화학|
|-|-|-|-|-|
|우석|90|85|70|50|
|인아|80|90|80|70|
|나라|75|85|80|90|
|민정|90|95|90|100|

In [3]:
%reset -f
#과제 6
import pandas as pd
student_data = {'이름':['우석', '인아', '나라', '민정'],
                '국어':[90,80,75,90],
                '영어':[85,90,85,95],
                '물리':[70,80,80,90],
                '화학':[50,70,90,100] }
df=pd.DataFrame(student_data)
df.loc[:,'인문']=df.loc[:,'국어']+df.loc[:,'영어']
df.loc[:,'과학']=df.loc[:,'물리']+df.loc[:,'화학']
df.sort_values(by='과학',ascending=False,inplace=True)
print(df)

   이름  국어  영어  물리   화학   인문   과학
3  민정  90  95  90  100  185  190
2  나라  75  85  80   90  160  170
1  인아  80  90  80   70  170  150
0  우석  90  85  70   50  175  120

4.
1) iris3.csv 파일을 읽고 (첫번째 행을 column 이름으로)  
2) column 이름을 'feat1','feat2','feat3','feat4','name'으로 변경하고  
3) 처음 3개 행을 print하고  
4) 요약 정보를 print하고  
5) 통계 정보를 print하고  
6) 각 열 데이터의 고유값 개수를 print하고  
7) 'feat2' 열의 최대값 print  
8) 'feat4' 열의 표준 편차 print   
9) 'feat1'과 'feat3'의 상관계수를 출력하는 코드를 작성 하시오.

In [5]:
%reset -f
#과제 7
import pandas as pd

read_csv = pd.read_csv('/content/sample_data/iris3.csv',header=0)
df=pd.DataFrame(read_csv)

df.columns=['feat1','feat2','feat3','feat4','name']
print(df.head(3))
print('\n')

print(df.info())
print('\n')

print(df.describe())
print('\n')

print(df.nunique())
print('\n')

df.loc[:,'feat2'].max()
print('\n')

df.loc[:,'feat4'].std()
print('\n')

df.loc[:,['feat1','feat3']].corr()
print('\n')

   feat1  feat2  feat3  feat4         name
0    5.1    3.5    1.4    0.2  Iris-setosa
1    4.9    3.0    1.4    0.2  Iris-setosa
2    4.7    3.2    1.3    0.2  Iris-setosa


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   feat1   150 non-null    float64
 1   feat2   150 non-null    float64
 2   feat3   150 non-null    float64
 3   feat4   150 non-null    float64
 4   name    150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


            feat1       feat2       feat3       feat4
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667
std      0.828066    0.433594    1.764420    0.763161
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000


feat1    35
feat2    23
feat3    43
feat4    22
name      3
dtype: int64

5.code에서 정의한 데이터에서   
1) 하나라도 NaN이 있는 행은 삭제하고 print하는 code  (df1에 저장 후 print)    
2) 모든 값이  NaN인  행을 삭제하고 print하는 code  (df2에 저장 후 print)   
3) NaN이 포함된 행을 삭제할때 데이터가 4개 이상 있어야 남기도록 하고  (df3)   print하는 code를 작성 하시오

In [6]:
%reset -f
#과제 8
import pandas as pd

import numpy as np

raw_data = {'name': ['Jason', np.nan, 'Tina', 'Jake', 'Amy'],
            'age': [42, np.nan, 36, np.nan, 73],
            'math': [4, np.nan, np.nan, 2, 3],
            'physics': [25, np.nan, np.nan, 62, 70],
             'korean': [25, np.nan, np.nan, 62, 70]}

df = pd.DataFrame(raw_data)
print(df)
df1=df[:]
df1.dropna(inplace=True)
print('\n')
print(df1)
print('\n')


df2=df[:]
df2.dropna(how='all',inplace=True)
print(df2)
print('\n')


df3=df[:]
df3.dropna(thresh=4,inplace=True)
print(df3)
print('\n')

    name   age  math  physics  korean
0  Jason  42.0   4.0     25.0    25.0
1    NaN   NaN   NaN      NaN     NaN
2   Tina  36.0   NaN      NaN     NaN
3   Jake   NaN   2.0     62.0    62.0
4    Amy  73.0   3.0     70.0    70.0


    name   age  math  physics  korean
0  Jason  42.0   4.0     25.0    25.0
4    Amy  73.0   3.0     70.0    70.0


    name   age  math  physics  korean
0  Jason  42.0   4.0     25.0    25.0
2   Tina  36.0   NaN      NaN     NaN
3   Jake   NaN   2.0     62.0    62.0
4    Amy  73.0   3.0     70.0    70.0


    name   age  math  physics  korean
0  Jason  42.0   4.0     25.0    25.0
3   Jake   NaN   2.0     62.0    62.0
4    Amy  73.0   3.0     70.0    70.0

/tmp/ipykernel_2404/4146293105.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.dropna(inplace=True)
/tmp/ipykernel_2404/4146293105.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.dropna(how='all',inplace=True)
/tmp/ipykernel_2404/4146293105.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.dropna(thresh=4,inplace=True)

6.아래 code에서 정의하는 데이터 프레임에서    
1) 중복 행을 제거 하고 print하는 code(df1)  
2) c1,c3을 기준으로 중복행을 제거 하고 print하는 code(df2)  
를 작성 하시오.

In [7]:
%reset -f
#과제 10
import pandas as pd

df=pd.DataFrame({'c1':['a','a','b','a','b'],
                 'c2':[2,1,2,1,2],
                 'c3':[1,1,2,2,2]})
print(df)
df1 = df[:]
df1.drop_duplicates(inplace=True)
print('\n')
print(df1)
print('\n')

df2 = df[:]
df2.drop_duplicates(subset=['c1','c3'],inplace=True)
print(df2)

  c1  c2  c3
0  a   2   1
1  a   1   1
2  b   2   2
3  a   1   2
4  b   2   2


  c1  c2  c3
0  a   2   1
1  a   1   1
2  b   2   2
3  a   1   2


  c1  c2  c3
0  a   2   1
2  b   2   2
3  a   1   2

/tmp/ipykernel_2404/447032287.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop_duplicates(inplace=True)
/tmp/ipykernel_2404/447032287.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop_duplicates(subset=['c1','c3'],inplace=True)

5주차 실습

In [ ]:
import pandas as pd

data_list = {'이름':['우석','인아','나라','민정','서준'], '나이':[17, 14, 12, 19, 15], '구분':['고등','중등','초등','고등','중등'], '취미':['독서','산책','축구','독서','농구'], '학교':['선경','한국','우성','효성','상성']}
df = pd.DataFrame(data_list)
print(df)
print('\n')
# '이름' 열을 새로운 인덱스로 지정하고, df 객체에 변경사항 반영
df.set_index(['이름'], inplace=True)
print(df)
print('\n')

# '취미' 열 삭제
df.drop('취미', axis=1, inplace=True)
print(df)
print('\n')

# '나라' 행 삭제
df.drop('나라', axis=0, inplace=True)
print(df)
print('\n')

# '지민' 행 이름을 이용해 추가하여 '16, 중등, 효성' 데이터를 저장
df.loc['지민'] = [16, '중등', '효성']
print(df)
print('\n')

# column 이름을 '학교'에서 '교명'으로 변경
df.rename(columns={'학교':'교명'}, inplace=True)
print(df)
print('\n')

# 우석과 인아의 교명을 선경1, 한국1로 변경하고
df.loc['우석':'인아', '교명'] = ['선경1', '학교1']
print(df)
print('\n')

df.sort_values(by='나이',ascending=True,inplace=True)
print(df)
print('\n')

df.sort_values(by=['교명','나이'],ascending=[True,False],inplace=True)
print(df)
print('\n')

df['국적'] = '한국'
print(df)

   이름  나이  구분  취미  학교
0  우석  17  고등  독서  선경
1  인아  14  중등  산책  한국
2  나라  12  초등  축구  우성
3  민정  19  고등  독서  효성
4  서준  15  중등  농구  상성


    나이  구분  취미  학교
이름
우석  17  고등  독서  선경
인아  14  중등  산책  한국
나라  12  초등  축구  우성
민정  19  고등  독서  효성
서준  15  중등  농구  상성


    나이  구분  학교
이름
우석  17  고등  선경
인아  14  중등  한국
나라  12  초등  우성
민정  19  고등  효성
서준  15  중등  상성


    나이  구분  학교
이름
우석  17  고등  선경
인아  14  중등  한국
민정  19  고등  효성
서준  15  중등  상성


    나이  구분  학교
이름
우석  17  고등  선경
인아  14  중등  한국
민정  19  고등  효성
서준  15  중등  상성
지민  16  중등  효성


    나이  구분  교명
이름
우석  17  고등  선경
인아  14  중등  한국
민정  19  고등  효성
서준  15  중등  상성
지민  16  중등  효성


    나이  구분   교명
이름
우석  17  고등  선경1
인아  14  중등  학교1
민정  19  고등   효성
서준  15  중등   상성
지민  16  중등   효성


    나이  구분   교명
이름
인아  14  중등  학교1
서준  15  중등   상성
지민  16  중등   효성
우석  17  고등  선경1
민정  19  고등   효성


    나이  구분   교명
이름
서준  15  중등   상성
우석  17  고등  선경1
인아  14  중등  학교1
민정  19  고등   효성
지민  16  중등   효성


    나이  구분   교명  국적
이름
서준  15  중등   상성  한국
우석  17  고등  선경1  한국
인아  14  중등  학교1  한국
민정  19  고등   효성  한국
지민  16  중등   효성  한국